### ISSUE TITLE
Works, but does not work again unless I reboot after running it once

### ISSUE THREAD

**Issue by hosua** [naztronaut/dancyPi-audio-reactive-led#47]
First, when I run one of the visualizations, everything works flawlessly. 

However, once I close the program and try to open it again I get this error. 

``` 
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock  
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock  
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock  
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock  
ALSA lib pcm_oss.c:377:(_snd_pcm_oss_open) Unknown field port
ALSA lib pcm_oss.c:377:(_snd_pcm_oss_open) Unknown field port
ALSA lib pulse.c:243:(pulse_connect) PulseAudio: Unable to connect: Connection refused

ALSA lib pulse.c:243:(pulse_connect) PulseAudio: Unable to connect: Connection refused

ALSA lib pcm_a52.c:823:(_snd_pcm_a52_open) a52 is only for playback
ALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM iec958:{AES0 0x6 AES1 0x82 
AES2 0x0 AES3 0x2  CARD 1}
ALSA lib pcm_usb_stream.c:486:(_snd_pcm_usb_stream_open) Invalid type for card     
ALSA lib pcm_usb_stream.c:486:(_snd_pcm_usb_stream_open) Invalid type for card     
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock  
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock  
Traceback (most recent call last):
  File "/home/pi/dancyPi-audio-reactive-led/python/visualization.py", line 368, in 
<module>
    microphone.start_stream(microphone_update)
  File "/home/pi/dancyPi-audio-reactive-led/python/microphone.py", line 14, in start_stream
    frames_per_buffer=frames_per_buffer)
  File "/usr/local/lib/python3.7/dist-packages/pyaudio.py", line 750, in open      
    stream = Stream(self, *args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/pyaudio.py", line 441, in __init__  
    self._stream = pa.open(**arguments)
OSError: [Errno -9996] Invalid input device (no default output device)
```

Is there something I'm missing? I'm running this on a Raspberry Pi 3 b+ with the Raspbian OS. Also, I apologize if this should be obvious, I'm a bit of a noob.

**Comment by hosua** [comment]
Nevermind lol! I actually just found out that Ctrl+Z puts a process in the background, not actually close it. Since it was running the background while I was trying to start it, it wouldn't work. Whoops lol.
