### ISSUE TITLE
Lots of stuff I don't understand!

### ISSUE THREAD

**Issue by Unhallowed1949** [naztronaut/dancyPi-audio-reactive-led#52]
I'm extremely new to raspberry pi. Can anyone help?

pi@raspberrypi:~/dancyPi-audio-reactive-led/python $ sudo python3 visualization.py scroll
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
Traceback (most recent call last):
  File "visualization.py", line 368, in <module>
    microphone.start_stream(microphone_update)
  File "/home/pi/dancyPi-audio-reactive-led/python/microphone.py", line 14, in start_stream
    frames_per_buffer=frames_per_buffer)
  File "/usr/local/lib/python3.7/dist-packages/pyaudio.py", line 750, in open
    stream = Stream(self, *args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/pyaudio.py", line 441, in __init__
    self._stream = pa.open(**arguments)
OSError: [Errno -9996] Invalid input device (no default output device)

and prior to that when I installed Python 3, warning near the end.

Collecting numpy
  Downloading https://www.piwheels.org/simple/numpy/numpy-1.21.2-cp37-cp37m-linux_armv7l.whl (12.3 MB)
     |████████████████████████████████| 12.3 MB 7.8 kB/s
Collecting scipy==1.4.1
  Downloading https://www.piwheels.org/simple/scipy/scipy-1.4.1-cp37-cp37m-linux_armv7l.whl (50.7 MB)
     |████████████████████████████████| 50.7 MB 185 bytes/s
Collecting pyaudio
  Downloading https://www.piwheels.org/simple/pyaudio/PyAudio-0.2.11-cp37-cp37m-linux_armv7l.whl (53 kB)
     |████████████████████████████████| 53 kB 17 kB/s
Collecting pyqtgraph
  Downloading https://www.piwheels.org/simple/pyqtgraph/pyqtgraph-0.12.2-py3-none-any.whl (959 kB)
     |████████████████████████████████| 959 kB 346 kB/s
Installing collected packages: numpy, scipy, pyqtgraph, pyaudio
Successfully installed numpy-1.21.2 pyaudio-0.2.11 pyqtgraph-0.12.2 scipy-1.4.1
**_WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
================== Compl_**eted Installing Numpy, Scipy, PyAudio, PyQtgraph ==================
================== Start Installing rpi_ws281x ==================
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting rpi_ws281x
  Downloading https://www.piwheels.org/simple/rpi-ws281x/rpi_ws281x-4.3.0-cp37-cp37m-linux_armv7l.whl (116 kB)
     |████████████████████████████████| 116 kB 355 kB/s
Installing collected packages: rpi-ws281x
Successfully installed rpi-ws281x-4.3.0
**_WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv_**
================== Completed Installing rpi_ws281x ==================
================== Copying asound.conf ==================
================== Completed copying to /etc/asound.conf ==================
================== Creating backup of alsa.conf ==================
================== Completed backup of alsa.conf -> alsa.conf.bak ==================
================== Replacing text in alsa.conf ==================
================== Completed replacing text in alsa.conf =============

Please help out a noob lol

**Comment by naztronaut** [comment]
The warning you're getting after installation is fine to ignore. It just doesn't like that you're running things as sudo but it's necessary to control the hardware, the Pi won't work without it. 

As for the error you're seeing when trying to run it, it's saying t hat the mic isn't being detected. 

- Can you post outputs of these commands:
  - `cat /proc/asound/cards`
  - `cat /etc/modules`
  - `arecord -l`
  - `aplay -l`

The `arecord` output should give you a list of devices attached to your Pi. You want to make sure that whatever mic you are connected to is the number found in `/etc/asound.conf` - by default the installer adds card number `1` to the configuration: https://github.com/naztronaut/dancyPi-audio-reactive-led/blob/master/python/install/asound.conf

You'll just have to change the '1' to whatever number your device is.

**Comment by Unhallowed1949** [comment]
I donno. I'm at a loss here. I typoed in "dancypi-audio-reactive-led" and it says no such file or directory. Do I have to redo it every time I cycle my Pi? Maybe I should learn a thing or two about the Pi first lol

________________________________

**Comment by Unhallowed1949** [comment]
pi@raspberrypi:~ $ cat /proc/asound/cards
 0 [b1             ]: bcm2835_hdmi - bcm2835 HDMI 1
                      bcm2835 HDMI 1
 1 [Headphones     ]: bcm2835_headpho - bcm2835 Headphones
                      bcm2835 Headphones
 2 [Device         ]: USB-Audio - USB PnP Sound Device
                      C-Media Electronics Inc. USB PnP Sound Device at usb-0000:01:00.0-1.4, full spe
pi@raspberrypi:~ $ cat /etc/modules
# /etc/modules: kernel modules to load at boot time.
#
# This file contains the names of kernel modules that should be loaded
# at boot time, one per line. Lines beginning with "#" are ignored.

pi@raspberrypi:~ $ arecord -1
arecord: invalid option -- '1'
Try `arecord --help' for more information.
pi@raspberrypi:~ $ aplay -1
aplay: invalid option -- '1'

**Comment by naztronaut** [comment]
You're getting the FPS so that means it's working. Your settings look good. Are the lights not working?

**Comment by nmc5** [comment]
Hi, I am having this issue. I ran those commands and I got similar outputs. The only one that is a little different is aplay:

**** List of PLAYBACK Hardware Devices ****
card 0: Headphones [bcm2835 HDMI 1], device 0: bcm2835 HDMI 1 [bcm2835 Headphones]
Subdevices: 8/8
Subdevice #0: subdevice #0
Subdevice#1: subdevice #1
Subdevice #2: subdevice #2
Subdevice #3: subdevice #3
Subdevice #4: subdevice #4
Subdevice#5: subdevice #1
Subdevice #6: subdevice #6
Subdevice #7: subdevice #7
Subdevice #8: subdevice #8

But my lights are still not working.
