### ISSUE TITLE
Can't Run even after disabling pcm 

### ISSUE THREAD

**Issue by maxtannn** [naztronaut/dancyPi-audio-reactive-led#6]
Tried disabling like the video tutorials did, followed almost every step from the video and the thread. 
Tested the lights by running the examples files and it works fine. Connection is for sure right. 

Please help, I'm not a super experience coder and it will be great if you could explain to me with written directions!
I am currently working on a light experience relating to how lights would affect an individual for school. This is a basic opening for us to see how it will work for our testing only. 

The following is code prompt after trying to run visualization. Thank you very much

pi@raspberrypi:~/dancyPi-audio-reactive-led/python $ sudo python visualization.py scroll
Expression 'alsa_snd_pcm_hw_params_set_period_size_near( pcm, hwParams, &alsaPeriodFrames, &dir )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 924
ALSA lib pcm_dmix.c:1108:(snd_pcm_dmix_open) unable to open slave
ALSA lib confmisc.c:1281:(snd_func_refer) Unable to find definition 'defaults.bluealsa.device'
ALSA lib conf.c:4568:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5036:(snd_config_expand) Args evaluate error: No such file or directory
ALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM bluealsa
ALSA lib confmisc.c:1281:(snd_func_refer) Unable to find definition 'defaults.bluealsa.device'
ALSA lib conf.c:4568:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5036:(snd_config_expand) Args evaluate error: No such file or directory
ALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM bluealsa
ALSA lib pcm_dmix.c:1108:(snd_pcm_dmix_open) unable to open slave
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
Expression 'paInvalidSampleRate' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 2048
Expression 'PaAlsaStreamComponent_InitialConfigure( &self->capture, inParams, self->primeBuffers, hwParamsCapture, &realSr )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 2719
Expression 'PaAlsaStream_Configure( stream, inputParameters, outputParameters, sampleRate, framesPerBuffer, &inputLatency, &outputLatency, &hostBufferSizeMode )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 2843
Traceback (most recent call last):
  File "visualization.py", line 370, in <module>
    microphone.start_stream(microphone_update)
  File "/home/pi/dancyPi-audio-reactive-led/python/microphone.py", line 14, in start_stream
    frames_per_buffer=frames_per_buffer)
  File "/usr/lib/python2.7/dist-packages/pyaudio.py", line 750, in open
    stream = Stream(self, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/pyaudio.py", line 441, in __init__
    self._stream = pa.open(**arguments)
IOError: [Errno -9997] Invalid sample rate

**Comment by naztronaut** [comment]
Looks like maybe it can't find your alsa.conf file. Can you look at this section and confirm that you did this step: https://github.com/naztronaut/dancyPi-audio-reactive-led#audio-device-configuration

And do you have a microphone plugged in? There needs to be a mic plugged in to run the script as well.

**Comment by maxtannn** [comment]
> Looks like maybe it can't find your alsa.conf file. Can you look at this section and confirm that you did this step: https://github.com/naztronaut/dancyPi-audio-reactive-led#audio-device-configuration
> 
> And do you have a microphone plugged in? There needs to be a mic plugged in to run the script as well.

Hi Sir, 

Thank you for your speedy response. I did have my snowball USB microphone attached to it and I did follow the configuration to create the asound file.  If you would like me to, I can provide you screenshots of all the directory and it will be great if you could be specific with what you would like to see in order to help to get this to work. 

Thank you - Max

**Comment by naztronaut** [comment]
I just did a quick google and it seems like Snowball USB mics use a frequency of 44.1 khz. So on line 57 of `python/config.py` try changing the `MIC_RATE` to 44100:

https://github.com/naztronaut/dancyPi-audio-reactive-led/blob/c63b85188999a4565a372f5e37b511c6c60538b6/python/config.py#L57

If that doesn't work and if everything else looks good, I would recommend just scrapping this and starting from the beginning. Maybe something didn't get installed correctly. Let me know if you're still getting the same error.

**Comment by naztronaut** [comment]
Hi Max, 

Not sure if you're still having this issue, one thing that helped someone else in a similar situation is to turn off the Pi, plug in the mic, and then turn it back on. It seems that sometimes the Pi has a hard time picking up new devices if they are plugged in while the pi is on.

**Comment by naztronaut** [comment]
I just updated the tutorial and repo this past week. I tried automating as much as I can.  Hope it helps!

Here's the written tutorial: https://www.easyprogramming.net/raspberrypi/audio_reactive_led.php
And video tutorial: https://www.youtube.com/watch?v=7YLF-N0596I

**Comment by farhandsome** [comment]
@naztronaut  Hey, not to hijack the thread, but I'm actually having the same issue. See below:

Oct 31 16:45:44 raspberrypi librespot[629]: ALSA lib pcm_dsnoop.c:638:(snd_pcm_dsnoop_open) unable to open slave
Oct 31 16:45:44 raspberrypi librespot[629]: ALSA lib confmisc.c:1281:(snd_func_refer) Unable to find definition 'defaults.bluealsa.device'
Oct 31 16:45:44 raspberrypi librespot[629]: ALSA lib conf.c:4568:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
Oct 31 16:45:44 raspberrypi librespot[629]: ALSA lib conf.c:5036:(snd_config_expand) Args evaluate error: No such file or directory
Oct 31 16:45:44 raspberrypi librespot[629]: ALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM bluealsa
Oct 31 16:45:44 raspberrypi librespot[629]: ALSA lib confmisc.c:1281:(snd_func_refer) Unable to find definition 'defaults.bluealsa.device'
Oct 31 16:45:44 raspberrypi librespot[629]: ALSA lib conf.c:4568:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
Oct 31 16:45:44 raspberrypi librespot[629]: ALSA lib conf.c:5036:(snd_config_expand) Args evaluate error: No such file or directory
Oct 31 16:45:44 raspberrypi librespot[629]: ALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM bluealsa
Oct 31 16:45:44 raspberrypi librespot[629]: Cannot connect to server socket err = No such file or directory
Oct 31 16:45:44 raspberrypi librespot[629]: Cannot connect to server request channel
Oct 31 16:45:44 raspberrypi librespot[629]: jack server is not running or cannot be started
Oct 31 16:45:44 raspberrypi librespot[629]: JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
Oct 31 16:45:44 raspberrypi librespot[629]: JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
Oct 31 16:45:44 raspberrypi librespot[629]: Cannot connect to server socket err = No such file or directory
Oct 31 16:45:44 raspberrypi librespot[629]: Cannot connect to server request channel
Oct 31 16:45:44 raspberrypi librespot[629]: jack server is not running or cannot be started
Oct 31 16:45:44 raspberrypi librespot[629]: JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
Oct 31 16:45:44 raspberrypi librespot[629]: JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
Oct 31 16:45:44 raspberrypi librespot[629]: ALSA lib pcm_oss.c:377:(_snd_pcm_oss_open) Unknown field port
Oct 31 16:45:44 raspberrypi librespot[629]: ALSA lib pcm_oss.c:377:(_snd_pcm_oss_open) Unknown field port
Oct 31 16:45:44 raspberrypi librespot[629]: ALSA lib pulse.c:243:(pulse_connect) PulseAudio: Unable to connect: Connection refused
Oct 31 16:45:44 raspberrypi librespot[629]: ALSA lib pulse.c:243:(pulse_connect) PulseAudio: Unable to connect: Connection refused
Oct 31 16:45:44 raspberrypi librespot[629]: ALSA lib pcm_a52.c:823:(_snd_pcm_a52_open) a52 is only for playback
Oct 31 16:45:44 raspberrypi librespot[629]: ALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM iec958:{AES0 0x6 AES1 0x82 AES2 0x0 AES3 0x2  CARD 0}
Oct 31 16:45:44 raspberrypi librespot[629]: ALSA lib pcm_usb_stream.c:486:(_snd_pcm_usb_stream_open) Invalid type for card
Oct 31 16:45:44 raspberrypi librespot[629]: ALSA lib pcm_usb_stream.c:486:(_snd_pcm_usb_stream_open) Invalid type for card
Oct 31 16:45:45 raspberrypi librespot[629]: Cannot connect to server socket err = No such file or directory


I have a custom asound.conf file.. not sure if that makes a difference. here it is: 
# Change to the card number or name that you want to be the default control card.
# Default: 0
defaults.ctl.card 0

# Change to the card number or name that you want to be the default playback card.
# It should usually be the same as defaults.ctl.card.
# Default: 0
defaults.pcm.card 0

# Change to the device number that you want to be the default device on the default card.
# 0 or 1 is usually the correct device number.
# Default: 0
defaults.pcm.device 0

# Change to the subdevice number that you want to be the default subdevice on the default device.
# Should rarely need to be changed.
# Default: -1
defaults.pcm.subdevice -1

defaults.pcm.rate_converter speexrate_medium

pcm.!default {
    type plug
    slave {
        channels 2
        rate 48000
        format S16_LE
        pcm {
            type softvol
            slave.pcm {
                type dmix
                ipc_key 1024
                ipc_perm 0660
                ipc_gid audio
                slowptr true
                hw_ptr_alignment roundup
                slave {
                    pcm {
                        type hw
                        card {
                            @func refer
                            name defaults.pcm.card
                        }
                        device {
                            @func refer
                            name defaults.pcm.device
                        }
                        subdevice {
                            @func refer
                            name defaults.pcm.subdevice
                        }
                    }
                    channels 2
                    period_size 0
                    buffer_size 0
                    buffer_time 0
                    period_time 250000
                    periods 4
                    rate 48000
                    format S16_LE
                }
                bindings {
                    0 0
                    1 1
                }
            }
            control {
                name PCM
                card {
                    @func refer
                    name defaults.ctl.card
                }
            }
        }
    }
}

pcm.spotify {
    type plug
    slave {
        channels 2
        rate 48000
        format S16_LE
        pcm {
            type softvol
            slave.pcm default
            control {
                name spotify
                card {
                    @func refer
                    name defaults.ctl.card
                }
            }
        }
    }
}

pcm.alexa {
    type plug
    slave {
        channels 2
        rate 48000
        format S16_LE
        pcm {
            type softvol
            slave.pcm default
            control {
                name alexa
                card {
                    @func refer
                    name defaults.ctl.card
                }
            }
        }
    }
}

**Comment by farhandsome** [comment]
@naztronaut Running it on a Logitech C270 if that makes a difference!

**Comment by naztronaut** [comment]
Your default card is set to device 0. Is that correct? Can you output the results of this:

```
cat /proc/asound/cards
```

Did you use the installer that I have in the repo or did you make the edits manually?

**Comment by farhandsome** [comment]
@naztronaut No worries I figured it out! Thanks though. I have another question, but I'll ask in a different thread.

**Comment by naztronaut** [comment]
@farhandsome Awesome!! Glad you figured that out. What was the issue? Your resolution may help others in the future.
