### ISSUE TITLE
AttributeError: module 'pyaudio' has no attribute 'PyAudio'

### ISSUE THREAD

**Issue by oskar18j** [naztronaut/dancyPi-audio-reactive-led#69]
i get this error when i run the visualization script

sudo python3 visualization.py scroll
Traceback (most recent call last):
  File "/home/pi3b/dancyPi-audio-reactive-led/python/visualization.py", line 368, in <module>
    microphone.start_stream(microphone_update)
  File "/home/pi3b/dancyPi-audio-reactive-led/python/microphone.py", line 8, in start_stream
    p = pyaudio.PyAudio()
AttributeError: module 'pyaudio' has no attribute 'PyAudio'

**Comment by oskar18j** [comment]
uninstalled and reinstalled pyaudio and it worked
